### ISSUE TITLE
Whitelist and blacklist not working when using Botania’s ring of magnetization

### ISSUE THREAD

**Issue by Dimentive** [comp500/Demagnetize#6]
I want to the demagnetizer to only prevent me from picking up canola seeds, crystallized canola seeds, and empowered canola seeds from Actually Additions. I’m using an advanced demagnetizer. I’m not sure whether to put it on whitelist or blacklist (for instance, does “whitelist” mean “only stop magnetizing for the selected items” or “keep these items from being affected from the demagnetization”? I assume it’s the former), but I’ve tried both whitelist and blacklist, and I’ve configured it to only affect these three types of canola seeds, but the demagnetizer keeps _any_ items from being magnetized in its vicinity regardless.

![Demagnetizer bug](https://user-images.githubusercontent.com/34230933/56013252-2853d580-5cf0-11e9-9c08-3241f100b827.png)

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579))
* **Minecraft:** 1.12.2 (duh)
* **Forge:** 14.23.5.2781
* **Demagnetize:** [1.0.1](https://minecraft.curseforge.com/projects/demagnetize/files/2657779) (latest)

**Comment by comp500** [comment]
What magnet are you using with it? Your configuration seems to be correct, as "Whitelist" does mean "only demagnetise these items".

**Comment by Dimentive** [comment]
I am using the [ring of magnetization](https://ftb.gamepedia.com/Ring_of_Magnetization) from [Botania](https://minecraft.curseforge.com/projects/botania).

I thought that the ring was broken at first, but it turns out it was the demagnetizer causing it to stop functioning in its vicinity. My ring of magnetization doesn’t magnetize any items while I’m near the demagnetizer.

This could still be an issue on Botania’s side; I’m not sure.

I’m using version [r1.10-361](https://minecraft.curseforge.com/projects/botania/files/2698039) (latest) of Botania.

**Comment by comp500** [comment]
Yeah, that's an issue with how I implemented the Botania compatibility. My mod just emulates a Solegnolia, which doesn't have an item filter, so the item filter is ignored.

I've been intending to fix this for quite a while (see #1) but never got around to it. I'll submit a PR to Botania today to make it directly compatible, so my Solegnolia emulation won't be needed.

**Comment by comp500** [comment]
I've submitted a PR to Botania at https://github.com/Vazkii/Botania/pull/2888.

When it has been merged and a build of Botania is published with the fix in it, I'll release a version of my mod that disables the explicit Botania compatibility when that build (or newer) of Botania is detected. This will also fix #1.

**Comment by Dimentive** [comment]
Awesome! Thanks! 🙌

**Comment by comp500** [comment]
Once the build of Botania is released, you just need to go into my mod's config and disable the Botania compatibility to fix this behaviour.

When I get some free time, I'll put in some logic to turn it off by default when a new enough build of Botania is detected (or just regardless of Botania version, because if you have my mod updated you probably have Botania updated anyway). I have some other things I want to fix in my mod as well (#7, config syncing to client, and a bit of code cleanup), so I'll do all of that soon.

**Comment by Dimentive** [comment]
Disable the Botania compatibility? Do you mean this won’t be fixed?

**Comment by comp500** [comment]
No, I mean disable the setting in my mod for "Botania compatibility" because Botania has directly implemented checking of the NBT tag that my mod adds, so the explicit compatibility method (that ignores the whitelist) isn't needed. For now, once you have updated Botania to a build including my changes, it will continue to work the same way as before until you disable the setting in my mod for explicit compatibility with Botania.

**Comment by Dimentive** [comment]
All right, I understand. I’ll be doing that once the new version of Botania is released. Thanks again for the PR!

**Comment by comp500** [comment]
Fixed by https://github.com/comp500/Demagnetize/commit/e79c22f0272c24337cdb38b7def1499e21aac625, released in 1.12.2-1.1.0 (pending CurseForge approval)
